### ISSUE TITLE
don't use the pointer of interface

### ISSUE THREAD

**Issue by LinkShen** [brucespang/go-tcpinfo#1]
Hi,
`func GetsockoptTCPInfo(conn *net.Conn) (*TCPInfo, error)`
the api declared here has a problem that you use *net.Conn, and it should be net.Conn. Go says developer should not use pointer of the interface type.
And it is really frustrating when it comes to the following code
```
// s.conn is *net.TCPConn
tcpinfo.GetsocketoptTCPInfo(s.conn) //compile error
tcpinfo.GetsocketoptTCPInfo((s.conn).(*net.Conn)) //compile error
```

**Comment by brucespang** [comment]
I haven't worked on this project for a while, but that seems annoying. If you want to submit a PR for the change you have in mind, I'd be happy to incorporate it!

**Comment by LinkShen** [comment]
#2
